module.exports = {
    POST_BOARD_LOG_SUCCESS: 'POST_BOARD_LOG_SUCCESS',
    POST_COMMENT_LOG_SUCCESS: 'POST_COMMENT_LOG_SUCCESS',
    POST_LIKE_LOG_SUCCESS: 'POST_LIKE_LOG_SUCCESS',
    POST_USER_LOG_SUCCESS: 'POST_USER_LOG_SUCCESS',
    POST_ERROR_LOG_SUCCESS: 'POST_ERROR_LOG_SUCCESS',
    POST_EXCEPT_LOG_SUCCESS: 'POST_EXCEPT_LOG_SUCCESS',
    POST_PROFILE_IMAGE_SUCCESS: 'POST_PROFILE_IMAGE_SUCCESS',
    POST_PROFILE_IMAGE_FAIL: 'POST_PROFILE_IMAGE_FAIL',
    NO_FILE_UPLOADED: 'NO_FILE_UPLOADED',
    NO_STREAM: 'NO_STREAM',
    NOT_VIDEO_STREAM_TYPE: 'NOT_VIDEO_STREAM_TYPE',
    UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
};
