module.exports = {
    POST_BOARD_LOG_SUCCESS: 'POST_BOARD_LOG_SUCCESS',
    POST_COMMENT_LOG_SUCCESS: 'POST_COMMENT_LOG_SUCCESS',
    POST_LIKE_LOG_SUCCESS: 'POST_LIKE_LOG_SUCCESS',
    POST_USER_LOG_SUCCESS: 'POST_USER_LOG_SUCCESS',
    POST_ERROR_LOG_SUCCESS: 'POST_ERROR_LOG_SUCCESS',
    POST_EXCEPT_LOG_SUCCESS: 'POST_EXCEPT_LOG_SUCCESS',
};
